service: hom-api-service
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-warmup
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  runtimeManagement: auto
  memorySize: 512
  timeout: 10
  versionFunctions: true
  tracing:
    lambda: true
  vpc:
    securityGroupIds:
      - 'sg-0bebb4a2d0ea2a673'
    subnetIds:
      - 'subnet-00de4b393c96085a0'
      - 'subnet-035c8cac300cfbf38'
      - 'subnet-04228e4aed2ce0e35'
      - 'subnet-09ecb135c1481416d'
      - 'subnet-084b74ef0a9f87510'
      - 'subnet-0748e6b6c36037d28'
  iam:
    role:
      statements:
        - Effect: Allow
          # TODO: Provide stricter policy
          Action:
            - 'ec2:*'
            - 'docdb-elastic:*'
            - 'memorydb:*'
            - 's3:*'
            - 'mq:*'
          Resource:
            - '*'

package:
  individually: true
  patterns:
    - '!src/**'
    - '!data/**'
    - '!libs/**'
    - '!local/**'

functions:
  graphql:
    handler: dist/packages/hom/graphql/index.handler
    events:
      - http:
          path: /graphql
          method: POST
          cors: true
    warmup:
      default:
        enabled: true
  fb-pull:
    handler: dist/packages/hom/fb-pull/index.handler
    events:
      - rabbitmq:
          arn: arn:aws:mq:us-east-1:077269188659:broker:HOM-MQ:b-d49c8b06-7316-42aa-852f-74f4ce4272e1
          queue: fb
          basicAuthArn: arn:aws:secretsmanager:us-east-1:077269188659:secret:MQAccess-5d5oAI
  fb-push:
    handler: dist/packages/hom/fb-push/index.handler
    events:
      - schedule:
          rate: rate(60 minutes)
  auth:
    handler: dist/packages/hom/auth/index.handler
    events:
      - http:
          path: /auth/test
          method: GET
          cors: true
      - http:
          path: /auth/fb
          method: GET
          cors: true
      - http:
          path: /auth/fb/redirect
          method: GET
          cors: true
      - http:
          path: /auth/google
          method: GET
          cors: true
      - http:
          path: /auth/google/redirect
          method: GET
          cors: true
      - http:
          path: /auth/twitter
          method: GET
          cors: true
      - http:
          path: /auth/twitter/redirect
          method: GET
          cors: true
    warmup:
      default:
        enabled: true

custom:
  # plugins
  serverless-offline:
    httpPort: 3000
    host: 0.0.0.0
    httpProxy: true
  warmup:
    default:
      enabled: true
      memorySize: 256
      name: warmer-default
      events:
        - schedule: 'cron(0/5 8-17 ? * MON-FRI *)'
      prewarm: true
